<?php

function siteinformation_form_system_site_information_settings_alter(&$form, $form_state, $form_id)
{

  // Add Site API Key field to 'Site Information' section
  $modulename = \Drupal::config('siteapikey.configuration')->get('siteapikey');
  $form['site_information']['siteinformation'] = array(
    '#type' => 'textfield',
    '#title' => t('Site API Key'),
    '#default_value' => $modulename ?: 'No API Key Yet',
    '#description' => t('An API Key to access site pages in JSON format.'),
  );

  // Change form submit button text to 'Update Configuration'
  $form['actions']['submit']['#value'] = t('Update configuration');

  // Handle form submission
  $form['#submit'][] = 'siteinformation_handler';
}

function siteinformation_handler($form, &$form_state)
{
  // Update the system variable Site API Key
  $config = \Drupal::configFactory()->getEditable('siteapikey.configuration');
  $new_modulename = $form_state->getValue(['siteinformation']);
  $config->set('siteapikey', $new_modulename);
  $config->save();

  // Add message that Site API Key has been set
  drupal_set_message("Successfully set Site API Key to " . $new_modulename);
}

/**
 * Implements hook_uninstall().
 */
function site_api_key_uninstall(){
  // Remove the previously set Site API Key configuration
  \Drupal::configFactory()->getEditable('siteapikey.configuration')->delete();
}
